### ISSUE TITLE
GitHub Presente  March 22, 2022 6PM CST

### ISSUE THREAD

**Issue by AndreaGriffiths11** [githubpresente/Meetup-ES#1]
**Date of event** : _March, 22_   <br>
**Region for event** :  LATAM_ <br>
**Language for event** : _Spanish._  <br>
**Language for Subtitles** : _Spanish_  <br>

**Theme / Topics for this event:** 
**Your 1 paragraph description should replace this line**
 

**Format** 

| Task| Status| Details |
| --- | --- | --- |
| Speaker Confirmation 1 | ✅  |  |
| Speaker Confirmation 2  |  ✅  |  |
| Generate event - StreamYard |  ✅  |  |
| Create event on Meetup | ✅  |  |
| Social media poster design | ✅  |   |
| Create short links | ✅  |   |
| Block for date and time event | ✅  |  |
| Tech Check with Speakers | ✅  |   |

# Weekly execution and DRIs

### <br> **Internal Host 1**
<br> **Internal host Name:** _add name here, and handle_
<br> **Internal host Content:** _add the topic here, include links to the slide deck, etc..._
- [x] Initial Contact
- [x] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft

_The External speakers, should talk about case studies  (theme relevant) using GitHub, civic tech, community, open source, getting started, technology._

### <br> **Status Speaker 1**
<br> **External Speaker Name:** _Tania Allard, @ixek_
<br> **External Speaker Content:** _add the topic here, include links to the slide deck, etc..._
- [x] Initial Contact
- [x] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft

### <br> **Status Speaker 2**
<br> **External Speaker Name:** _Stefanni Cavaletto, @stefanni_ch_
<br> **External Speaker Content:** _add the topic here, include links to the slide deck, etc..._
- [x] Initial Contact
- [x] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft

**Comment by DennyPerez18** [comment]
Done! ✅  https://youtu.be/JwdwzFWYLHc
