### ISSUE TITLE
Event schedule - Presente March 22

### ISSUE THREAD

**Issue by DennyPerez18** [githubpresente/Meetup-ES#17]

**Comment by DennyPerez18** [comment]
Hola @AndreaGriffiths11 Aqui voy a necesitar ayuda tuya o de Jaime. Por cierto, Me compartes el email de Jaime para agregarlo al time block por favor?

**Comment by AndreaGriffiths11** [comment]
claro es highfi13g@github.com, si quieres yo me encargo de la invitacion?
