### ISSUE TITLE
Special training event 30 minutes to merge en Spanish 6-28 4PM ET

### ISSUE THREAD

**Issue by AndreaGriffiths11** [githubpresente/Meetup-ES#27]
GItHub Actions with Gonzalo Pena
June 28, 2022 4PM

 
 
**Date of event** : _June, 28_   <br>
**Region for event** :  LATAM_ <br>
**Language for event** : _Spanish._  <br>
**Language for Subtitles** : _Spanish_  <br>

**Theme / Topics for this event:*Special training event 30 minutes GItHub Actions* 
****
 

**Format** 
Meetup virtual

| Task| Status| Details |
| --- | --- | --- |
| Speaker Confirmation 1 | ✅ | Gonzalo Peña |
| Generate event - StreamYard |  |  |
| Create event on Meetup |  ✅  |  https://www.meetup.com/githublatam/events/285890639/ |
| Social media poster design |   |  |
| Create short links | ✅ | https://github.co/acciones |
| Block for date and time event |   |  |
| Tech Check with Speaker | ✅ |   |
| Create Slide (deck) |  |   |

![Screen Shot 2022-05-31 at 12 48 40 PM](https://user-images.githubusercontent.com/38770890/171229625-90606e3d-0c91-432b-b9c7-cde0fb216aeb.png)

**Comment by DennyPerez18** [comment]
Done.     ✅
https://www.youtube.com/watch?v=vRu9eswr5OE
