### ISSUE TITLE
Create the event on Meetup platform - [Junio,29]

### ISSUE THREAD

**Issue by DennyPerez18** [githubpresente/Meetup-ES#29]
ENLACE AL EVENTO EN LA PLATAFORMA:
https://www.youtube.com/watch?v=qhaEJ345oZg

DESCRIPCION DEL EVENTO:

Hola, comunidad!

Esperamos que todos estén bien.

Este mes de junio estamos muy contentos de presentarles un panel donde estaremos celebrando el mes de los mantenedores de código abierto. El Mes del Mantenedor es una oportunidad para que los mantenedores se reúnan y compartan conocimientos y experiencias. Como siempre les estaremos presentando las novedades exclusivas de GitHub. 

**Tema:** Manteniendo Proyectos Código abierto

En esta ocacion contaremos con la presencia de los siguientes panelistas:

**Cristian Maureira-Fredes:** @cmaureir
Cristián, actualmente es un Líder de Equipo e Ingeniero de Software en 'The Qt Company'. En su tiempo libre, le gusta ayudar en comunidades enfocadas en Open Source, principalmente relacionadas a Python, Qt y C++.

**Andres Pineda:** @pinedax_
Andrés es un desarrollador de aplicaciones con un alto interés en Tecnologías móviles. Él es colaborador en distintas comunidades de desarrollo donde tiene la oportunidad de aportar de diferentes formas: ya sea programando, mentoreando, organizando eventos y/o participando como charlista. En su tiempo libre, Andrés disfruta hacer ejercicios, jugar videojuegos o simplemente ver series de televisión.

**Santiago Debus:** @santidebus
https://github.com/sandes

Como siempre, muchas gracias a nuestros distinguidos ponentes, síguelos en sus redes sociales y no te olvides de compartir esta página con tus amigos.

¡Nos vemos pronto!
Únete al stream: [link](https://www.youtube.com/watch?v=qhaEJ345oZg)

**Comment by AndreaGriffiths11** [comment]
Hola @DennyPerez18 quieres programarlo en meetup

**Comment by DennyPerez18** [comment]
@AndreaGriffiths11 
Listo ✅ Aún no le di a publicar. 
https://www.meetup.com/githublatam/events/286581795/
