### ISSUE TITLE
[AUG 3] Virtual Meetup /GitHub Presente [Spanish]

### ISSUE THREAD

**Issue by DennyPerez18** [githubpresente/Meetup-ES#31]
**Date of event** : _July,27_   <br>
**Region for event** :  LATAM_ <br>
**Language for event** : _Spanish._  <br>
**Language for Subtitles** : _Spanish_  <br>

**Theme / Topics for this event:** 
**Your 1 paragraph description should replace this line**
 

**Format** 

| Task| Status| Details |
| --- | --- | --- |
| Speaker Confirmation 1 | ✅ | Pamela Bustamante |
| Speaker Confirmation 2  | ✅ | Manuel Zapata |
| Generate event - StreamYard | ✅  | https://streamyard.com/dq7hqn57et |
| Create event on Meetup | ✅ | https://www.meetup.com/githublatam/events/287381203/ |
| Social media poster design | ✅ | https://www.canva.com/design/DAFHVJhMGeA/D28dsKQeQkLZe6cbRdlcEQ/edit |
| Create short links | ✅   | https://github.co/Agosto |
| Block for date and time event | ✅ | |
| Tech Check with Speaker 1 |   |   |
| Tech Check with Speaker 2 |    |   |
| Create Slide (deck) | ✅ |  https://docs.google.com/presentation/d/1PXFLgjF_vFF1b7euiGN_pSRR1l91KpToF51tDpwhrUU/edit#slide=id.g13aad640152_0_74 |

# Weekly execution and DRIs

### <br> **Status Speaker 1**
<br> **External Speaker Name:** 
<br> **External Speaker Content:** _add the topic here, include links to the slide deck, etc..._
- [ ] Initial Contact
- [ ] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft

### <br> **Status Speaker 2**
<br> **External Speaker Name:** 
<br> **External Speaker Content:** _add the topic here, include links to the slide deck, etc..._
- [ ] Initial Contact
- [ ] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft
| 20 Min | breakout room - move to zoom for a group conversation |  stick around, chat and call to action |

**Comment by DennyPerez18** [comment]
@AndreaGriffiths11 Ya quedó coordinado con los speakers. Meetup presente Miércoles 3 de Agosto. Mas arriba en el detallle esta lo que ya esta listo.

**Comment by AndreaGriffiths11** [comment]
Updated

**Comment by DennyPerez18** [comment]
@AndreaGriffiths11 Cuando puedas porfa me compartes el deck para ir poniendo los diseños de los speakers y ver si encuentro algunos eventos gratuitos para ponerlos 😊

**Comment by DennyPerez18** [comment]
Done! https://www.meetup.com/githublatam/events/287381203/
