### ISSUE TITLE
[Octubre] Virtual Meetup GitHub Presente [Spanish]

### ISSUE THREAD

**Issue by DennyPerez18** [githubpresente/Meetup-ES#34]
**Date of event** : _??_   <br>
**Region for event** :  LATAM_ <br>
**Language for event** : _Spanish._  <br>
**Language for Subtitles** : _Spanish_  <br>

**Theme / Topics for this event:**  Hablemos de proyectos Open Source
**Your 1 paragraph description should replace this line**
 

**Format** 

| Task| Status| Details |
| --- | --- | --- |
| Speaker Confirmation 1 | ✅ | Cristián Maureira |
| Speaker Confirmation 2  | ✅ | Pablo García |
| Generate event - StreamYard | ✅ | [https://streamyard.com/rufchfdeux](https://www.google.com/url?q=https://streamyard.com/rufchfdeux&sa=D&source=calendar&usd=2&usg=AOvVaw1XhrDSmDjxnEgmcVyQ1o_H) |
| Create the event on Meetup | ✅  | https://www.meetup.com/githublatam/events/289311084/?isFirstPublish=true |
| Social media poster design | ✅  | https://www.canva.com/design/DAFHVJhMGeA/D28dsKQeQkLZe6cbRdlcEQ/edit |
| Create short links |   |  |
| Block for date and time event | ✅  |  |
| Tech Check with Speaker 1 |   |   |
| Tech Check with Speaker 2 |    |   |
| Create Slide (deck) |  |   |

# Weekly execution and DRIs

### <br> **Status Speaker 1**
<br> **External Speaker Name:** 
<br> **External Speaker Content:** _add the topic here, include links to the slide deck, etc..._
- [ ] Initial Contact
- [ ] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft

### <br> **Status Speaker 2**
<br> **External Speaker Name:** 
<br> **External Speaker Content:** _add the topic here, include links to the slide deck, etc..._
- [ X] Initial Contact
- [ ] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft
| 20 Min | breakout room - move to zoom for a group conversation |  stick around, chat and call to action |

**Comment by DennyPerez18** [comment]
@AndreaGriffiths11  Hola. Estoy haciendo el intento de ver si hacemos un meetup para la semana que viene tipo miércoles 26 o Jueves 27. Te parecen OK esas fechas? Sería para cerrar el mes con este tema: "Hablemos de Proyectos Open Source"

**Comment by AndreaGriffiths11** [comment]
@DennyPerez18 si esta bien! Ya tienes speakers? También, a ver si @ lizarragadev se anima a ser tu cohost?

**Comment by AndreaGriffiths11** [comment]
El lunes vemos el formulario juntas, decidiste fecha?

**Comment by DennyPerez18** [comment]
Estoy confirmando con los speakers si les conviene Jueves a las 5:pm ET

**Comment by DennyPerez18** [comment]
Link to the event:
https://www.youtube.com/watch?v=oMLTN5RDD_k
