### ISSUE TITLE
GitHub Presente ES Junio 2023 

### ISSUE THREAD

**Issue by DennyPerez18** [githubpresente/Meetup-ES#40]
**Date of event** : _Jun, 08_   <br>
**Region for event** :  LATAM_ <br>
**Language for event** : _Spanish._  <br>
**Language for Subtitles** : _Spanish_  <br>

**Theme / Topics for this event:** 
**Your 1 paragraph description should replace this line**
 

**Format** 

| Task| Status| Details |
| --- | --- | --- |
| Speaker Confirmation 1 |  |  |
| Speaker Confirmation 2  |   |  |
| Generate event - StreamYard |  |  |
| Create event on Meetup |    |  |
| Social media poster design |   |  |
| Create short links |   |  |
| Block for date and time event |   |  |
| Tech Check with Speaker 1 |   |   |
| Tech Check with Speaker 2 |    |   |
| Create Slide (deck) |  |   |

# Weekly execution and DRIs

### <br> **Status Speaker 1**
<br> **External Speaker Name:** 
<br> **External Speaker Content:** _add the topic here, include links to the slide deck, etc..._
- [ ] Initial Contact
- [ ] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft

### <br> **Status Speaker 2**
<br> **External Speaker Name:** 
<br> **External Speaker Content:** _add the topic here, include links to the slide deck, etc..._
- [ ] Initial Contact
- [ ] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft
| 20 Min | breakout room - move to zoom for a group conversation |  stick around, chat and call to action |

**Comment by lizarragadev** [comment]
Hola @DennyPerez18  y @AndreaGriffiths11 ,

Creo que aún estoy a tiempo, hice los videitos para el Meetup de Hoy, https://drive.google.com/drive/folders/1M-et0w_D2cxY5w302zQl1q0BPyL15c80?usp=sharing  ahi va el enlace, ya no hice de estados, creo que no fué muy útil hehe me avisan si necesitan algo más, estaré viendo la transmisión. Gracias.

**Comment by lizarragadev** [comment]
Hola @AndreaGriffiths11 @DennyPerez18  una consulta, hay presente de Julio? para poder hacer los recursos multimedia :) gracias.

**Comment by AndreaGriffiths11** [comment]
Hola @lizarragadev mil gracias! Para Julio vamos a tomar un break. Volvemos en Agosto apenas tenga los detalles abro el issue

**Comment by lizarragadev** [comment]
Gracias
