### ISSUE TITLE
GitHub Presente April 20, 2022 6PM CST

### ISSUE THREAD

**Issue by DennyPerez18** [githubpresente/Meetup-ES#7]
**Date of event** : _Abril, 20_   <br>
**Region for event** :  LATAM_ <br>
**Language for event** : _Spanish._  <br>
**Language for Subtitles** : _Spanish_  <br>

**Theme / Topics for this event:** 
**Your 1 paragraph description should replace this line**
 

**Format** 

| Task| Status| Details |
| --- | --- | --- |
| Speaker Confirmation 1 | ✅  | Bruno Capuano |
| Speaker Confirmation 2  |  ✅  | Bea Gandica |
| Generate event - StreamYard | ✅  | https://streamyard.com/cwb4hjh2cc |
| Create event on Meetup | ✅   | https://www.youtube.com/watch?v=aQpF8coM5Vw |
| Social media poster design | ✅  |  https://www.canva.com/design/DAE8foIsI-M/1jGb_ruNJI_XeDWixybKnQ/edit |
| Create short links |  ✅  | https://github.co/abril  |
| Block for date and time event | ✅  | Ready on Google Calendar |
| Tech Check with Speaker 1 |  ✅  | Done on April 14 - 10:00 EST  |
| Tech Check with Speaker 2 |  ✅  | Done on April 14 - 4:45 EST  |
| Create Slide (deck) |  ✅  | https://docs.google.com/presentation/d/13PJ6ghLQTWNoEn8862it7V7KHt4FfE_GlziiiJzq7gY/edit#slide=id.g101ff79cac1_0_0  |

# Weekly execution and DRIs

### <br> **Internal Host 1**
<br> **Internal host Name:** _add name here, and handle_
<br> **Internal host Content:** _add the topic here, include links to the slide deck, etc..._
- [x] Initial Contact
- [x] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft

_The External speakers, should talk about case studies  (theme relevant) using GitHub, civic tech, community, open-source, getting started, technology._

### <br> **Status Speaker 1**
<br> **External Speaker Name:** _Bruno Capuano, @elbruno_
<br> **External Speaker Content:** _add the topic here, include links to the slide deck, etc..._
- [x] Initial Contact
- [x] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft

### <br> **Status Speaker 2**
<br> **External Speaker Name:** _Beatriz Gandica, @beagandica_
<br> **External Speaker Content:** _add the topic here, include links to the slide deck, etc..._
- [x] Initial Contact
- [x] Locked for Date & Time
- [ ] Content rough idea 
- [ ] Content rough draft
- [ ] Content final draft

**Comment by DennyPerez18** [comment]
@AndreaGriffiths11 
En lo que estuve buscando speakers para el mes de Marzo. Conseguí que Bea Gandica y El Bruno confirmaran su participación para el evento de Abril. Me gustaría saber qué fecha sugieres el 19 o 20 de Abril para de una vez hacer que nos aparten el día. Puse el dia 20 pero podemos modificarlo.

**Comment by AndreaGriffiths11** [comment]
El 20 está bien Denny! Muchas gracias ❤️❤️❤️

**Comment by DennyPerez18** [comment]
Done! https://www.youtube.com/watch?v=VyIgaFft_8Q
