### ISSUE TITLE
Social media poster design

### ISSUE THREAD

**Issue by DennyPerez18** [githubpresente/Meetup-ES#9]
https://www.canva.com/teams

Create designs to post on social media

| **Platform** | **Status** | 
| --- | --- |
| Meetup | https://www.canva.com/design/DAE6TjqaVnA/GJUNtizV_Rb3hskx9Xv-1w/edit?utm_content=DAE6TjqaVnA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton | 
| Twitter | | 
| Facebook | | 
| Instagram | | 
| StreamYard intro | |

**Comment by AndreaGriffiths11** [comment]
Yes! my action is broken, was supposed to add via issues... I'll send you the creds

**Comment by DennyPerez18** [comment]
@AndreaGriffiths11 😁  Remember, when you have time, add the GitHub Presente template to Canva, please.

**Comment by AndreaGriffiths11** [comment]
Here we go my friend, a million sorries for the delay: https://www.canva.com/design/DAE2Auxfi0M/share/preview?token=UH0eR2g__aTKCo3FLXbj-g&role=EDITOR&utm_content=DAE2Auxfi0M&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by DennyPerez18** [comment]
Thanks, @AndreaGriffiths11 You rock! 🚀

**Comment by DennyPerez18** [comment]
@AndreaGriffiths11  Propuesta de diseño para el evento de Marzo
https://www.canva.com/design/DAE6TjqaVnA/GJUNtizV_Rb3hskx9Xv-1w/edit

**Comment by AndreaGriffiths11** [comment]
Perfecto 🚢

**Comment by DennyPerez18** [comment]
Canva Design: https://www.canva.com/design/DAE6TjqaVnA/GJUNtizV_Rb3hskx9Xv-1w/edit?utm_content=DAE6TjqaVnA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
